# Generated by Django 6.0.6 on 2026-06-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_leader_note', models.TextField(default='Song Leader gives announcements.')),
                ('preacher_note', models.TextField(default='Sunday Preacher gives Scripture Reader the passage.')),
            ],
        ),
    ]
