# Generated by Django 6.0.6 on 2026-06-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0002_role_permanently_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_type', models.CharField(choices=[('SUN_AM', 'Sunday Morning'), ('SUN_PM', 'Sunday Evening'), ('WED_PM', 'Wednesday Evening')], max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.directoryentry')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.role')),
            ],
        ),
    ]
