# Generated by Django 6.0.6 on 2026-06-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='service_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Assignment'), ('SUN_AM', 'Sunday Morning'), ('SUN_PM', 'Sunday Evening'), ('WED_PM', 'Wednesday Evening')], max_length=10),
        ),
    ]
