# Generated by Django 6.0.6 on 2026-06-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
