# Generated by Django 6.0.6 on 2026-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_notes'),
        ('directory', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['date', 'service_type', 'role'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='service_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Assignment'), ('Sunday Morning', 'Sunday Morning'), ('Sunday Evening', 'Sunday Evening'), ('Wednesday Evening', 'Wednesday Evening')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('date', 'service_type', 'role')},
        ),
    ]
