# Generated by Django 6.0.6 on 2026-06-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='service_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Assignments'), ('SUNDAY MORNING', 'Sunday Morning'), ('SUNDAY EVENING', 'Sunday Evening'), ('WEDNESDAY EVENING', 'Wednesday Evening')], max_length=30),
        ),
    ]
