# Generated by Django 6.0.6 on 2026-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='service_type',
            field=models.CharField(choices=[('MONTHLY', 'MONTHLY ASSIGNMENTS'), ('SUNDAY MORNING', 'SUNDAY MORNING'), ('SUNDAY EVENING', 'SUNDAY EVENING'), ('WEDNESDAY EVENING', 'WEDNESDAY EVENING')], max_length=30),
        ),
    ]
