# Generated by Django 6.0.6 on 2026-08-10 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_alter_assignment_service_type'),
        ('directory', '0006_directoryentry_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.directoryentry'),
        ),
    ]
