# Generated by Django 6.0.6 on 2026-06-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender_restriction', models.CharField(choices=[('MEN', 'Men Only'), ('WOMEN', 'Women Only'), ('ANY', 'Any Member')], default='ANY', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_leader_note', models.TextField(default='Song Leader is responsible for any opening announcements.')),
                ('preacher_note', models.TextField(default='Selected speaker is to select the Scripture Reading and give it to the reader.')),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Member'), ('INACTIVE', 'Inactive Member')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('roles', models.ManyToManyField(blank=True, to='directory.role')),
            ],
        ),
    ]
