# Generated by Django 6.0.6 on 2026-06-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permanently_assigned_to',
            field=models.CharField(blank=True, help_text='If this role is always done by one person (e.g., Steve Hickman), enter their name here.', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='gender_restriction',
            field=models.CharField(choices=[('MEN', 'Men Only'), ('WOMEN', 'Women Only'), ('ANY', 'Any Member'), ('FAMILY', 'Family Role')], default='ANY', max_length=10),
        ),
    ]
