# Generated by Django 6.0.6 on 2026-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_role_permanently_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
