# Generated by Django 6.0.6 on 2026-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='gender_restriction',
            field=models.CharField(choices=[('MEN', 'Male'), ('WOMEN', 'Female'), ('FAMILY', 'Family')], default='MEN', max_length=10),
        ),
    ]
