# Generated by Django 6.0.6 on 2026-06-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_alter_role_gender_restriction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directoryentry',
            old_name='roles',
            new_name='assigned_roles',
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='raw_roles',
            field=models.TextField(blank=True),
        ),
    ]
