# Generated by Django 6.0.6 on 2026-07-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_rename_roles_directoryentry_assigned_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryentry',
            name='family_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
